# Site settings
title: Marie Mc Guinness
email: mcguinnessmarie@gmail.com
description: >
  personal portfolio
baseurl: "/portfolio"
url: ""
github_username:  mmguinness

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  # - node_modules/
  # - vendor/bundle/
  # - vendor/cache/
  # - vendor/gems/
  # - vendor/ruby/
